# Basic Information 
title: Debanjan Goswami
position: Doctoral Researcher
affiliation: Florida State University
affiliation_link: https://www.fsu.edu/
affiliation_logo: ./assets/img/FSU.svg
email: dgoswami (at) fsu.edu

# Search Engine Optimization (SEO)
keywords: debanjan goswami, goswami debanjan, debanjangoswami, goswamidebanjan, debanjan, goswami
canonical: https://debanjangoswami.com
description: Debanjan Goswami is a doctoral student in Computer Science at the Florida State University. His research lies in Computer Vision, Language Models, and Active Learning.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Ce-FKAYAAAAJ&hl=en
github_link: https://github.com/iamdebanjang
linkedin: https://www.linkedin.com/in/debanjan-goswami/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: /assets/img/myIMG.jpg

# Footnotes
footnote: Page is updated on a monthly basis.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: h0jZgr1ySUDVlbruM-CmlYoinb22hKSRz7KFnMRgsP4

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
